import type { Metadata } from "next";
import "@/app/globals.css";
import { UserProvider } from "@/context/useUser";

export const metadata: Metadata = {
  title: "Livraria Fracaro",
  description: "Generated by Sandro Eduardo Fracaro",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <UserProvider>
          {children}
        </UserProvider>
      </body>
    </html>
  );
}
