import type { Metadata } from "next";
import "@/app/globals.css"
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Livraria Fracaro",
  description: "Generated by Sandro Eduardo Fracaro",
};

export default function GeneralLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <div className="min-h-screen">
        <Header/>
        {children}
      </div>
    </html>
  );
}
